# docker-compose.yml

services:
  docs:
    build: ./mkdocs
    volumes:
      - ./mkdocs:/docs
      - ./notebooks:/docs/My_Notes/notebooks:ro 
    ports:
      - "127.0.0.1:11415:8000" #修改端口
    command: serve -a 0.0.0.0:8000
  jupyter:
    build: ./jupyter
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/home/jovyan/work
    ports:
      - "127.0.0.1:11416:8888"   # 本機11401 → 容器8888（Jupyter）
    command: start-notebook.sh --ServerApp.token='' --ServerApp.password=''